### ISSUE TITLE
Could not find a declaration file for module 'deepmerge' after npm run build on new project

### ISSUE THREAD

**Issue by asicfr** [assurance-maladie-digital/vue-cli-preset#5] opened 2021-09-28 13:57 UTC
Hi,
On a new project created with :
      vue create projet1 --preset assurance-maladie-digital/vue-cli-preset
when we launch "npm run build", we have the following error : 
4:23 Could not find a declaration file for module 'deepmerge'. '/projet1/node_modules/deepmerge/dist/umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/deepmerge` if it exists or add a new declaration (.d.ts) file containing `declare module 'deepmerge';`
    2 | import { ExtendedVue } from 'vue/types/vue';
    3 |
  > 4 | import deepMerge from 'deepmerge';
      |                       ^
    5 |
    6 | import { IndexedObject } from '../../types';
    7 |

Have you any idea of the problem please ? 

Thanks

**Comment by Kelhel** [comment] 2021-09-29 07:48
Hello, I can't replication the problem, what are your versions of :
- node
- vue

Also, we recommend to use `yarn` instead of `npm`

Thanks

**Comment by asicfr** [comment] 2021-09-29 11:18
Hi
node -v
v14.4.0
npm -v
6.14.5
windows 10

cmd executed : 
npm install -g @vue/cli
vue create skvu --preset assurance-maladie-digital/vue-cli-preset   (no to all options )
npm run build

We are using npm as standard.

Thanks

**Comment by deraw** [comment] 2021-10-04 14:35
Hi,

I was able to repdoduce the issue using npm as package manager:

```bash
vue create skvu --packageManager=npm --preset assurance-maladie-digital/vue-cli-preset
```

## Cause

The issue is caused by the dependency resolution of npm, as it installs the version 1.5.2 of `deepmerge` instead of the version 4.2.2.
The 1.5.2 version does not contains TypeScript typings, thus causing the error you're seeing.

## Resolution

To fix this issue, you can run the following command to install the required version of deepmerge:

```bash
npm install -D deepmerge@^4.2.2
```

We'll fix this issue in the default template soon.

**Comment by deraw** [comment] 2021-10-19 17:09
This is fixed and will be released in the next version!

**Closed as completed by deraw** 2021-10-19 17:09 UTC
Labels: bug
